services:
  - type: web
    name: course-recommendation-app
    env: python
    pythonVersion: 3.11.0
    buildCommand: |
      python -m pip install --upgrade pip
      pip install wheel
      pip install -r requirements.txt
    startCommand: gunicorn app:app
    envVars:
      - key: GEMINI_API_KEY
        sync: false