services:
  - type: web
    name: course-recommendation-app
    env: python
    pythonVersion: 3.11.0
    buildCommand: |
      python -m pip install --upgrade pip
      pip install wheel
      pip install -r requirements.txt
    startCommand: gunicorn app:app --bind 0.0.0.0:$PORT --log-level debug
    envVars:
      - key: GOOGLE_API_KEY
        sync: false
      - key: PYTHONUNBUFFERED
        value: "1"
    healthCheckPath: /