services:
  - type: web
    name: course-recommendation-app
    env: python
    buildCommand: |
      apt-get update -y
      apt-get install -y python3-dev build-essential
      pip install --upgrade pip
      pip install -r requirements.txt
    startCommand: gunicorn app:app
    envVars:
      - key: GEMINI_API_KEY
        sync: false